// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrtrl51xdPSFZQU0vPGMHM6F0F3ugzrsY',
    appId: '1:483900241472:web:224c60df51f4f670fb51a5',
    messagingSenderId: '483900241472',
    projectId: 'erp-test-979d7',
    authDomain: 'erp-test-979d7.firebaseapp.com',
    storageBucket: 'erp-test-979d7.appspot.com',
    measurementId: 'G-C0QWQ34HX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4iEpx9b67vgMMLklNItnZ_y7gfP6wook',
    appId: '1:483900241472:android:036231815c911ef4fb51a5',
    messagingSenderId: '483900241472',
    projectId: 'erp-test-979d7',
    storageBucket: 'erp-test-979d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXR_c1XRJujQKnpECbBfRcQAzfF8lvTtU',
    appId: '1:483900241472:ios:0b9526e87e7c48ccfb51a5',
    messagingSenderId: '483900241472',
    projectId: 'erp-test-979d7',
    storageBucket: 'erp-test-979d7.appspot.com',
    iosBundleId: 'com.example.testEep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXR_c1XRJujQKnpECbBfRcQAzfF8lvTtU',
    appId: '1:483900241472:ios:44802658855fd966fb51a5',
    messagingSenderId: '483900241472',
    projectId: 'erp-test-979d7',
    storageBucket: 'erp-test-979d7.appspot.com',
    iosBundleId: 'com.example.testEep.RunnerTests',
  );
}
